Repository rainlanguage/rain.orderbook, pull requests merged in 2024-09, with the labels that each got.

#810 update subgraph crate and app subgraph usage
  .vscode/settings.json
  crates/cli/src/commands/order/detail.rs
  crates/cli/src/commands/order/list.rs
  crates/cli/src/commands/order_take/detail.rs
  crates/cli/src/commands/order_take/list.rs
  crates/cli/src/commands/vault/detail.rs
  crates/cli/src/commands/vault/list.rs
  crates/cli/src/commands/vault/list_balance_changes.rs
  crates/quote/src/cli/mod.rs
  crates/quote/src/quote.rs
  crates/subgraph/queries/multiOrderDetail.graphql
  crates/subgraph/queries/orderDetail.graphql
  crates/subgraph/queries/orderTakeDetail.graphql
  crates/subgraph/queries/orderTakesList.graphql
  crates/subgraph/queries/ordersList.graphql
  crates/subgraph/queries/vaultBalanceChangesList.graphql
  crates/subgraph/queries/vaultDetail.graphql
  crates/subgraph/queries/vaultsList.graphql
  crates/subgraph/schema/orderbook.graphql
  crates/subgraph/src/types/order_detail.rs
  crates/subgraph/src/types/order_detail_traits.rs
  crates/subgraph/src/types/order_take_detail.rs
  crates/subgraph/src/types/order_takes_list.rs
  crates/subgraph/src/types/orders_list.rs
  crates/subgraph/src/types/vault_balance_changes_list.rs
  crates/subgraph/src/types/vault_detail.rs
  crates/subgraph/src/types/vaults_list.rs
  crates/subgraph/tests/snapshots/batch_order_test__batch_order_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_take_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_takes_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/orders_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/vault_balance_changes_test__vault_balance_changes_list_query_gql_output.snap
  crates/subgraph/tests/snapshots/vault_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/vaults_test__vaults_query_gql_output.snap
  tauri-app/src-tauri/src/commands/order_quote.rs
  tauri-app/src-tauri/src/commands/trade_debug.rs
  tauri-app/src-tauri/src/error.rs
  tauri-app/src/lib/components/charts/VaultBalanceChart.test.ts
  tauri-app/src/lib/components/detail/OrderDetail.svelte
  tauri-app/src/lib/components/detail/VaultDetail.svelte
  tauri-app/src/lib/components/detail/VaultDetail.test.ts
  tauri-app/src/lib/components/tables/OrderTradesListTable.test.ts
  tauri-app/src/lib/components/tables/OrdersListTable.svelte
  tauri-app/src/lib/components/tables/OrdersListTable.test.ts
  tauri-app/src/lib/components/tables/VaultBalanceChangesTable.test.ts
  tauri-app/src/lib/components/tables/VaultListTable.svelte
  tauri-app/src/lib/components/tables/VaultListTable.test.ts
  tauri-app/src/lib/queries/orderDetail.ts
  tauri-app/src/lib/queries/orderQuote.ts
  tauri-app/src/lib/queries/vaultBalanceChangesList.ts
  tauri-app/src/lib/queries/vaultDetail.ts
  tauri-app/src/lib/services/historicalOrderCharts.ts
  tauri-app/src/lib/utils/vault.ts
  test-js/quote/test.test.ts
Labels: bug, Tauri, ui/ux, general update, rust, subgraph

#804 shakeout dotrain with deployments
  crates/cli/src/commands/order/calldata.rs
  crates/cli/src/commands/order/filter.rs
  crates/cli/src/commands/order/mod.rs
  crates/cli/src/commands/order/orderbook_address.rs
  crates/common/src/dotrain_order/filter.rs
  crates/common/src/dotrain_order/mod.rs
  crates/common/src/frontmatter.rs
  crates/integration_tests/src/lib.rs
  crates/settings/src/chart.rs
  crates/settings/src/config_source.rs
  crates/settings/src/plot_source.rs
Labels: CLI, new feature, rust

#827 order by last added
  crates/subgraph/queries/orderDetail.graphql
  crates/subgraph/queries/ordersList.graphql
  crates/subgraph/src/types/orders_list.rs
  crates/subgraph/tests/snapshots/orders_test__orders_query_gql_output.snap
  tauri-app/src/lib/components/tables/OrdersListTable.svelte
  tauri-app/src/lib/components/tables/OrdersListTable.test.ts
Labels: enhancement, ui/ux, general update, rust, subgraph

#829 Order filtering by watchlist
  crates/cli/src/commands/order/list.rs
  crates/cli/src/subgraph.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/types/common.rs
  crates/subgraph/src/types/order.rs
  crates/subgraph/tests/orders_test.rs
  crates/subgraph/tests/snapshots/orders_test__orders_query_gql_output.snap
  tauri-app/src-tauri/src/commands/order.rs
  tauri-app/src/lib/components/ListViewOrderbookSelector.svelte
  tauri-app/src/lib/components/dropdown/DropdownCheckbox.svelte
  tauri-app/src/lib/components/dropdown/DropdownOrderListWatchlist.svelte
  tauri-app/src/lib/components/dropdown/DropdownOrderListWatchlist.test.ts
  tauri-app/src/lib/components/tables/OrdersListTable.svelte
  tauri-app/src/lib/queries/ordersList.ts
  tauri-app/src/lib/stores/settings.ts
Labels: enhancement

#835 local evm test helper
  Cargo.lock
  Cargo.toml
  crates/bindings/Cargo.toml
  crates/cli/Cargo.toml
  crates/common/Cargo.toml
  crates/common/src/replays/mod.rs
  crates/env/Cargo.toml
  crates/integration_tests/Cargo.toml
  crates/integration_tests/src/lib.rs
  crates/quote/Cargo.toml
  crates/settings/Cargo.toml
  crates/subgraph/Cargo.toml
  crates/test_fixtures/Cargo.toml
  crates/test_fixtures/src/lib.rs
  tauri-app/src-tauri/Cargo.lock
  test/util/concrete/TestERC20.sol
Labels: enhancement, test, rust

#832 Vault filtering by watchlist
  crates/cli/src/commands/vault/list.rs
  crates/cli/src/subgraph.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/types/common.rs
  crates/subgraph/src/types/vault.rs
  crates/subgraph/tests/snapshots/vaults_test__vaults_query_gql_output.snap
  crates/subgraph/tests/vaults_test.rs
  tauri-app/src-tauri/src/commands/vault.rs
  tauri-app/src/lib/components/tables/VaultListTable.svelte
  tauri-app/src/lib/queries/vaultList.ts
Labels: enhancement

#838 Order status filter
  crates/cli/src/commands/order/list.rs
  crates/cli/src/commands/vault/list.rs
  crates/cli/src/subgraph.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/types/common.rs
  tauri-app/src/lib/components/ListViewOrderbookSelector.svelte
  tauri-app/src/lib/components/dropdown/DropdownCheckbox.svelte
  tauri-app/src/lib/components/dropdown/DropdownOrderStatus.svelte
  tauri-app/src/lib/components/tables/OrdersListTable.svelte
  tauri-app/src/lib/queries/ordersList.ts
  tauri-app/src/lib/stores/settings.ts
Labels: enhancement

#854 fix tauri command batch order quote bug
  crates/test_fixtures/src/lib.rs
  tauri-app/src-tauri/src/commands/order_quote.rs
Labels: bug, Tauri, ui/ux, rust

#856 Hide zero balance vaults filter
  crates/cli/src/commands/order/list.rs
  crates/cli/src/commands/vault/list.rs
  crates/cli/src/subgraph.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/types/common.rs
  tauri-app/src/lib/components/ListViewOrderbookSelector.svelte
  tauri-app/src/lib/components/checkbox/Checkbox.svelte
  tauri-app/src/lib/components/checkbox/CheckboxZeroBalanceVault.svelte
  tauri-app/src/lib/components/dropdown/DropdownOrderStatus.svelte
  tauri-app/src/lib/components/tables/OrdersListTable.test.ts
  tauri-app/src/lib/components/tables/VaultListTable.svelte
  tauri-app/src/lib/components/tables/VaultListTable.test.ts
  tauri-app/src/lib/queries/vaultList.ts
  tauri-app/src/lib/stores/settings.ts
Labels: enhancement, ui/ux

#858 Order detail page vault simplification
  tauri-app/src/lib/components/ButtonVaultLink.svelte
  tauri-app/src/lib/components/detail/OrderDetail.svelte
  tauri-app/src/lib/components/detail/OrderDetail.test.ts
Labels: ui/ux

#857 Fixing input component
  tauri-app/src/lib/components/InputTokenAmount.svelte
Labels: bug, ui/ux

#859 Order list refetching on remove order
  tauri-app/src/lib/components/detail/OrderDetail.svelte
  tauri-app/src/lib/components/detail/OrderDetail.test.ts
  tauri-app/src/lib/components/modal/ModalOrderRemove.svelte
  tauri-app/src/lib/components/tables/OrdersListTable.svelte
  tauri-app/src/lib/components/tables/OrdersListTable.test.ts
  tauri-app/src/lib/services/modal.ts
Labels: bug, ui/ux

#884 `DotrainOrder` wasm/js api
  crates/cli/src/commands/order/filter.rs
  crates/common/src/dotrain_order/filter.rs
  crates/common/src/dotrain_order/mod.rs
  test-js/bindings/test.test.ts
  test-js/common/test.test.ts
  test-js/quote/test.test.ts
  test-js/tsconfig.json
Labels: js/wasm, general update, rust

#885 simulating add order
  crates/cli/src/commands/order/add.rs
  crates/common/src/add_order.rs
Labels: CLI, new feature, rust

#894 order vaults volume
  crates/cli/src/commands/order_take/detail.rs
  crates/cli/src/commands/order_take/list.rs
  crates/cli/src/commands/vault/list_balance_changes.rs
  crates/quote/src/quote.rs
  crates/subgraph/Cargo.toml
  crates/subgraph/src/lib.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/types/common.rs
  crates/subgraph/src/types/order_take.rs
  crates/subgraph/src/vol.rs
  crates/subgraph/tests/order_takes_test.rs
  crates/subgraph/tests/snapshots/batch_order_test__batch_order_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_take_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_takes_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/orders_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/vault_balance_changes_test__vault_balance_changes_list_query_gql_output.snap
  crates/subgraph/tests/snapshots/vault_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/vaults_test__vaults_query_gql_output.snap
  flake.nix
  tauri-app/src-tauri/src/commands/order_take.rs
  tauri-app/src-tauri/src/main.rs
  tauri-app/src/lib/components/Hash.svelte
  tauri-app/src/lib/components/charts/TableTimeFilters.svelte
  tauri-app/src/lib/components/charts/TableTimeFilters.test.svelte
  tauri-app/src/lib/components/charts/TableTimeFilters.test.ts
  tauri-app/src/lib/components/charts/VaultBalanceChart.test.ts
  tauri-app/src/lib/components/detail/OrderDetail.svelte
  tauri-app/src/lib/components/tables/OrderTradesListTable.svelte
  tauri-app/src/lib/components/tables/OrderTradesListTable.test.ts
  tauri-app/src/lib/components/tables/OrderVaultsVolTable.svelte
  tauri-app/src/lib/components/tables/OrderVaultsVolTable.test.ts
  tauri-app/src/lib/components/tables/TanstackAppTable.svelte
  tauri-app/src/lib/components/tables/VaultBalanceChangesTable.test.ts
  tauri-app/src/lib/queries/keys.ts
  tauri-app/src/lib/queries/orderTradesList.ts
  tauri-app/src/lib/queries/vaultBalanceChangesList.ts
  tauri-app/src/lib/services/historicalOrderCharts.ts
  tauri-app/src/lib/types/hash.ts
Labels: Tauri, ui/ux, new feature, rust, subgraph

#897 support yml anchors across dotrain and settings
  crates/cli/src/commands/chart/mod.rs
  crates/common/src/dotrain_order/mod.rs
  crates/common/src/frontmatter.rs
  crates/settings/src/config.rs
  crates/settings/src/config_source.rs
  tauri-app/src-tauri/src/commands/config.rs
Labels: general update, rust

#898 add order cli reindex version check
  crates/cli/src/commands/order/add.rs
Labels: CLI, general update, rust
