Repository rainlanguage/rain.orderbook, pull requests merged in 2024-10, with the labels that each got.

#900 rename order takes to trades
  crates/cli/Cargo.lock
  crates/cli/src/commands/mod.rs
  crates/cli/src/commands/trade/detail.rs
  crates/cli/src/commands/trade/list.rs
  crates/cli/src/commands/trade/mod.rs
  crates/cli/src/lib.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/types/mod.rs
  crates/subgraph/src/types/order_detail_traits.rs
  crates/subgraph/src/types/order_trade.rs
  crates/subgraph/src/utils/mod.rs
  crates/subgraph/src/utils/u256.rs
  crates/subgraph/tests/order_trade_test.rs
  crates/subgraph/tests/order_trades_test.rs
  crates/subgraph/tests/snapshots/order_trade_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_trades_test__vaults_query_gql_output.snap
  flake.nix
  tauri-app/src-tauri/src/commands/order_take.rs
  tauri-app/src-tauri/src/main.rs
  tauri-app/src/lib/components/TradesTable.svelte
  tauri-app/src/lib/components/tables/OrderTradesListTable.test.ts
  tauri-app/src/lib/queries/orderTradesList.ts
  tauri-app/src/lib/stores/order.ts
Labels: general update

#921 default `All Time` time filter for vol and trades
  tauri-app/src/lib/components/charts/TableTimeFilters.svelte
  tauri-app/src/lib/components/charts/TableTimeFilters.test.ts
  tauri-app/src/lib/components/tables/OrderTradesListTable.svelte
  tauri-app/src/lib/components/tables/OrderVaultsVolTable.svelte
Labels: ui/ux

#913 fix js package typeings field
  package-lock.json
  package.json
Labels: bug, js/wasm

#920 indicate order is live for vault list
  crates/subgraph/src/types/common.rs
  crates/subgraph/tests/snapshots/batch_order_test__batch_order_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/orders_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/vault_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/vaults_test__vaults_query_gql_output.snap
  tauri-app/src/lib/components/detail/VaultDetail.svelte
  tauri-app/src/lib/components/tables/VaultListTable.svelte
Labels: ui/ux, subgraph

#933 fix sg deployment
  subgraph/networks.json
  subgraph/src/clear.ts
Labels: bug

#935 debug subgraph
  crates/subgraph/schema/orderbook.graphql
  crates/subgraph/src/types/common.rs
  crates/subgraph/tests/snapshots/batch_order_test__batch_order_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/orders_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/vault_test__vaults_query_gql_output.snap
  crates/subgraph/tests/snapshots/vaults_test__vaults_query_gql_output.snap
  subgraph/schema.graphql
  subgraph/src/clear.ts
Labels: bug

#938 fix subgraph bugs
  crates/subgraph/schema/orderbook.graphql
  subgraph/schema.graphql
  subgraph/src/clear.ts
  subgraph/src/deposit.ts
  subgraph/src/erc20.ts
  subgraph/src/handlers.ts
  subgraph/src/meta.ts
  subgraph/src/order.ts
  subgraph/src/orderbook.ts
  subgraph/src/takeorder.ts
  subgraph/src/transaction.ts
  subgraph/src/withdraw.ts
  subgraph/tests/event-mocks.test.ts
  subgraph/tests/handlers/handle-addorder.test.ts
  subgraph/tests/handlers/handle-clear.test.ts
  subgraph/tests/handlers/handle-removeorder.test.ts
  subgraph/tests/handlers/handle-takeorder.test.ts
Labels: bug, Tauri, subgraph

#939 update subgraph tests
  subgraph/src/clear.ts
  subgraph/tests/event-mocks.test.ts
  subgraph/tests/handlers/handle-afterclear.test.ts
  subgraph/tests/handlers/handle-clear.test.ts
Labels: bug, test, subgraph

#922 net volume
  crates/subgraph/src/vol.rs
  tauri-app/src/lib/components/tables/OrderVaultsVolTable.svelte
  tauri-app/src/lib/components/tables/OrderVaultsVolTable.test.ts
Labels: ui/ux, rust

#957 Add wasm bindings for order quoting
  Cargo.lock
  crates/quote/src/js_api/impls.rs
  crates/quote/src/js_api/mod.rs
  crates/subgraph/Cargo.toml
  crates/subgraph/src/types/common.rs
  crates/subgraph/src/types/impls.rs
  crates/subgraph/src/types/mod.rs
  tauri-app/src-tauri/Cargo.lock
  test-js/quote/test.test.ts
Labels: js/wasm, new feature
