Repository rainlanguage/rain.orderbook, pull requests merged in 2024-05, with the labels that each got.

#564 small ui fix (ledger ux connection followup)
  tauri-app/src/lib/components/ModalConnect.svelte
  tauri-app/src/lib/components/ModalExecute.svelte
Labels: bug, enhancement, Tauri, ui/ux

#639 using orderJSONstring for the OrderV2 conversion
  Cargo.lock
  crates/subgraph/Cargo.toml
  crates/subgraph/src/types/order_detail.rs
  crates/subgraph/src/types/order_detail_traits.rs
Labels: bug

#647 fix darkmode text color on charts
  tauri-app/src/routes/+layout.svelte
Labels: enhancement

#646 random vault id
  .vscode/settings.json
  Cargo.lock
  crates/common/Cargo.toml
  crates/common/src/add_order.rs
  crates/settings/src/config_source.rs
  crates/settings/src/order.rs
Labels: enhancement

#658 update dotrain version
  Cargo.lock
  Cargo.toml
  tauri-app/package-lock.json
  tauri-app/package.json
Labels: enhancement

#664 update dotrain version
  Cargo.lock
  Cargo.toml
  tauri-app/package-lock.json
  tauri-app/package.json
Labels: enhancement

#667 update dotrain version
  Cargo.lock
  Cargo.toml
  tauri-app/package-lock.json
  tauri-app/package.json
Labels: enhancement
