Repository rainlanguage/rain.orderbook, pull requests merged in 2025-06, with the labels that each got.

#1831 Move remove transactions into context with constructor
  package-lock.json
  package.json
  packages/ui-components/src/__tests__/FixedBottomTransaction.test.ts
  packages/ui-components/src/__tests__/Transaction.test.ts
  packages/ui-components/src/__tests__/TransactionDetail.test.ts
  packages/ui-components/src/__tests__/TransactionList.test.ts
  packages/ui-components/src/__tests__/TransactionManager.test.ts
  packages/ui-components/src/__tests__/TransactionProvider.test.ts
  packages/ui-components/src/__tests__/awaitTransactionIndexing.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/__mocks__/mockTransactionStore.ts
  packages/ui-components/src/lib/components/transactions/FixedBottomTransaction.svelte
  packages/ui-components/src/lib/components/transactions/TransactionDetail.svelte
  packages/ui-components/src/lib/components/transactions/TransactionList.svelte
  packages/ui-components/src/lib/components/transactions/getStatusEmoji.ts
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/models/Transaction.ts
  packages/ui-components/src/lib/providers/transactions/TransactionManager.ts
  packages/ui-components/src/lib/providers/transactions/TransactionProvider.svelte
  packages/ui-components/src/lib/providers/transactions/context.ts
  packages/ui-components/src/lib/providers/transactions/useTransactions.ts
  packages/ui-components/src/lib/services/awaitTransactionIndexing.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/modal.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/__tests__/OrderRemoveModal.test.ts
  packages/webapp/src/__tests__/Sidebar.test.ts
  packages/webapp/src/__tests__/TransactionConfirmationModal.test.ts
  packages/webapp/src/__tests__/TransactionListener.test.ts
  packages/webapp/src/__tests__/TransactionModal.test.ts
  packages/webapp/src/__tests__/handleRemoveOrder.test.ts
  packages/webapp/src/__tests__/handleWalletConfirmation.test.ts
  packages/webapp/src/lib/components/OrderRemoveModal.svelte
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/lib/components/TransactionConfirmationModal.svelte
  packages/webapp/src/lib/components/TransactionModal.svelte
  packages/webapp/src/lib/components/TransactionProviderWrapper.svelte
  packages/webapp/src/lib/components/TransactionsListener.svelte
  packages/webapp/src/lib/services/handleRemoveOrder.ts
  packages/webapp/src/lib/services/handleWalletConfirmation.ts
  packages/webapp/src/lib/services/modal.ts
  packages/webapp/src/lib/stores/settings.ts
  packages/webapp/src/routes/+layout.svelte
  packages/webapp/src/routes/+layout.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/fullDeployment.test.ts
  packages/webapp/src/routes/layout.test.ts
  packages/webapp/src/routes/orders/[network]-[orderHash]/+page.svelte
  tauri-app/src/routes/+layout.svelte
Labels: enhancement, webapp

#1913 Replace dotrain order gui dummy constructor with class constructor
  Cargo.lock
  Cargo.toml
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/select_tokens.rs
  crates/js_api/src/gui/state_management.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/DepositInput.test.ts
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/__tests__/TokenIOInput.test.ts
  packages/ui-components/src/__tests__/handleShareChoices.test.ts
  packages/ui-components/test-setup.ts
  packages/webapp/src/__tests__/handleGuiInitialization.test.ts
  packages/webapp/src/lib/services/handleGuiInitialization.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/fullDeployment.test.ts
  tauri-app/src-tauri/Cargo.lock
  tauri-app/src-tauri/Cargo.toml
Labels: rust

#1912 updating settings.json to use specific commit to beat cache
  packages/webapp/src/routes/+layout.ts
Labels: bug

#1891 Move deploy to transaction manager
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/TransactionManager.test.ts
  packages/ui-components/src/__tests__/handleDeployment.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/__mocks__/mockTransactionStore.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/handleDeployment.ts
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/models/Transaction.ts
  packages/ui-components/src/lib/providers/transactions/TransactionManager.ts
  packages/ui-components/src/lib/services/awaitTransactionIndexing.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/modal.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/__tests__/DeployModal.test.ts
  packages/webapp/src/__tests__/TransactionListener.test.ts
  packages/webapp/src/__tests__/TransactionModal.test.ts
  packages/webapp/src/__tests__/handleAddOrder.test.ts
  packages/webapp/src/lib/components/DeployModal.svelte
  packages/webapp/src/lib/components/TransactionModal.svelte
  packages/webapp/src/lib/components/TransactionsListener.svelte
  packages/webapp/src/lib/services/handleAddOrder.ts
  packages/webapp/src/lib/services/handleDeploy.ts
  packages/webapp/src/lib/services/modal.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/fullDeployment.test.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/page.test.ts
  packages/webapp/src/routes/orders/+layout.svelte
  packages/webapp/src/routes/vaults/+layout.svelte
Labels: webapp

#1918 Refactor OrderbookYaml class constructor
  crates/js_api/src/yaml/mod.rs
  packages/orderbook/test/js_api/orderbookYaml.test.ts
Labels: rust

#1922 Replace gui configuration methods with a single function
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/errors/DeploymentStepsError.ts
Labels: webapp

#1919 Adding inline documentation for wasm bindings
  crates/common/src/dotrain_order/mod.rs
  crates/js_api/src/bindings/mod.rs
  crates/js_api/src/common/mod.rs
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/field_values.rs
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/gui/select_tokens.rs
  crates/js_api/src/gui/state_management.rs
  crates/js_api/src/subgraph/add_order.rs
  crates/js_api/src/subgraph/order.rs
  crates/js_api/src/subgraph/remove_order.rs
  crates/js_api/src/subgraph/trades.rs
  crates/js_api/src/subgraph/transaction.rs
  crates/js_api/src/subgraph/vault.rs
  crates/js_api/src/yaml/mod.rs
  crates/quote/src/js_api/mod.rs
Labels: rust

#1924 Add `getAllTokens` wasm binding to gui
  Cargo.lock
  crates/js_api/Cargo.toml
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/select_tokens.rs
  crates/js_api/src/gui/state_management.rs
  crates/settings/src/yaml/orderbook.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1936 Fix partial select token deserialization issue
  crates/js_api/src/gui/state_management.rs
  crates/settings/src/yaml/dotrain.rs
  packages/ui-components/src/lib/__mocks__/stores.ts
  packages/ui-components/vite.config.ts
Labels: bug
