Repository rainlanguage/rain.orderbook, pull requests merged in 2025-04, with the labels that each got.

#1569 Make subgraph url reactive to network key change
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
Labels: bug, webapp

#1534 useGui hook in SelectToken
  packages/ui-components/src/__tests__/SelectToken.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
Labels: webapp

#1474 Add OrderbookYaml class for returning yaml information
  Cargo.lock
  crates/js_api/Cargo.toml
  crates/js_api/src/lib.rs
  crates/js_api/src/yaml/mod.rs
  crates/settings/src/network.rs
  crates/settings/src/orderbook.rs
  crates/settings/src/yaml/orderbook.rs
  flake.nix
  packages/orderbook/test/js_api/orderbookYaml.test.ts
  tauri-app/src/lib/components/ModalExecute.svelte
  tauri-app/src/lib/components/ModalExecute.test.ts
  tauri-app/src/lib/services/order.ts
  tauri-app/src/tests/pickConfig.test.ts
Labels: rust

#1582 Add markdown support for description
  packages/ui-components/src/__tests__/DeploymentSectionHeader.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSectionHeader.svelte
Labels: bug, webapp

#1581 Bump viem version
  package-lock.json
  package.json
  packages/ui-components/package.json
  packages/webapp/package.json
Labels: bug, webapp

#1532 Fix order history/trades chart
  packages/ui-components/src/__tests__/TanstackLightweightChartLine.test.ts
  packages/ui-components/src/lib/components/charts/TanstackLightweightChartLine.svelte
  packages/ui-components/src/lib/components/charts/transformAndSortData.ts
  packages/ui-components/src/lib/index.ts
  packages/webapp/src/routes/vaults/[network]-[id]/+page.svelte
Labels: bug

#1496 Replace signer address in UI components
  packages/ui-components/src/__tests__/CheckboxMyItemsOnly.test.ts
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/ListViewOrderbookFilters.test.ts
  packages/ui-components/src/__tests__/OrderDetail.test.svelte
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/__tests__/WalletConnect.test.ts
  packages/ui-components/src/__tests__/getDeploymentTransactionArgs.test.ts
  packages/ui-components/src/lib/__mocks__/stores.ts
  packages/ui-components/src/lib/components/CheckboxMyItemsOnly.svelte
  packages/ui-components/src/lib/components/ListViewOrderbookFilters.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/getDeploymentTransactionArgs.ts
  packages/ui-components/src/lib/components/detail/DepositOrWithdrawButtons.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/components/tables/OrdersListTable.svelte
  packages/ui-components/src/lib/components/tables/VaultsListTable.svelte
  packages/ui-components/src/lib/components/wallet/WalletConnect.svelte
  packages/ui-components/src/lib/errors/DeploymentStepsError.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
  packages/webapp/src/routes/orders/+page.svelte
  packages/webapp/src/routes/orders/[network]-[orderHash]/+page.svelte
  packages/webapp/src/routes/vaults/+page.svelte
  packages/webapp/src/routes/vaults/[network]-[id]/+page.svelte
  tauri-app/src/routes/orders/+page.svelte
  tauri-app/src/routes/vaults/+page.svelte
Labels: webapp

#1538 Use gui hook in field definition input
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
Labels: webapp

#1539 Use gui in token io input
  packages/ui-components/src/__tests__/TokenIOInput.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
Labels: webapp

#1540 Use gui in deposit input
  packages/ui-components/src/__tests__/DepositInput.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DepositInput.svelte
Labels: webapp

#1594 Return correct error message from wasmencodedResult in DeploymentSteps
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
Labels: bug, webapp

#1541 useGui in ComposedRainlangModal
  packages/ui-components/src/__tests__/ComposedRainlangModal.test.ts
  packages/ui-components/src/lib/components/deployment/ComposedRainlangModal.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
Labels: webapp

#1577 Styled component for tooltip to prevent random shadows or low z-index
  packages/ui-components/src/lib/components/ButtonVaultLink.svelte
  packages/ui-components/src/lib/components/Hash.svelte
  packages/ui-components/src/lib/components/ListViewOrderbookFilters.svelte
  packages/ui-components/src/lib/components/Tooltip.svelte
  packages/ui-components/src/lib/components/detail/TanstackOrderQuote.svelte
Labels: bug, webapp

#1566 Add registry URL to all share links
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/handleShareChoices.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/services/handleShareChoices.ts
  packages/webapp/src/lib/__mocks__/stores.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/page.test.ts
Labels: bug, webapp

#1493 Pure function to prepare deployment transaction args and pass them to a deploy handler
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/DisclaimerModal.test.ts
  packages/ui-components/src/__tests__/getDeploymentTransactionArgs.test.ts
  packages/ui-components/src/__tests__/handleDeployment.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/getDeploymentTransactionArgs.ts
  packages/ui-components/src/lib/components/deployment/handleDeployment.ts
  packages/ui-components/src/lib/errors/DeploymentStepsError.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/lib/components/DeployModal.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
Labels: enhancement, webapp

#1477 Adding remote networks support to yaml
  crates/common/src/dotrain_order/mod.rs
  crates/settings/src/deployer.rs
  crates/settings/src/gui.rs
  crates/settings/src/lib.rs
  crates/settings/src/network.rs
  crates/settings/src/order.rs
  crates/settings/src/orderbook.rs
  crates/settings/src/remote/chains/chainid.rs
  crates/settings/src/remote_networks.rs
  crates/settings/src/scenario.rs
  crates/settings/src/token.rs
  crates/settings/src/yaml/cache.rs
  crates/settings/src/yaml/context.rs
  crates/settings/src/yaml/dotrain.rs
  crates/settings/src/yaml/mod.rs
  crates/settings/src/yaml/orderbook.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1483 Adding remote token support to yaml
  crates/common/src/dotrain_order/mod.rs
  crates/settings/src/gui.rs
  crates/settings/src/lib.rs
  crates/settings/src/network.rs
  crates/settings/src/order.rs
  crates/settings/src/remote/mod.rs
  crates/settings/src/remote/tokens.rs
  crates/settings/src/remote_networks.rs
  crates/settings/src/remote_tokens.rs
  crates/settings/src/token.rs
  crates/settings/src/yaml/cache.rs
  crates/settings/src/yaml/context.rs
  crates/settings/src/yaml/dotrain.rs
  crates/settings/src/yaml/mod.rs
  crates/settings/src/yaml/orderbook.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1596 Update field value setters and getters
  crates/js_api/src/gui/field_values.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
Labels: rust, webapp

#1597 Test updates for OrderDetail
  packages/ui-components/src/__tests__/OrderDetail.test.svelte
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/icon/Refresh.svelte
Labels: test

#1504 Generic VaultActionButton which propogates deposit/withdraw events to the page level from VaultDetail/Orderdetail
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/lib/components/detail/DepositOrWithdrawButtons.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
  packages/webapp/src/routes/orders/[network]-[orderHash]/+page.svelte
  packages/webapp/src/routes/vaults/[network]-[id]/+page.svelte
  tauri-app/src/routes/orders/[network]-[orderHash]/+page.svelte
  tauri-app/src/routes/vaults/[network]-[id]/+page.svelte
Labels: enhancement, webapp

#1575 Tests for /deploy layout load
  packages/webapp/src/routes/deploy/layout.test.ts
Labels: test

#1574 Tests for deploy/[strategyName]/[deploymentKey]/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/page.test.ts
Labels: test

#1512 RemoveOrderButton that calls the modal at page level
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/routes/orders/[network]-[orderHash]/+page.svelte
  tauri-app/src/routes/orders/[network]-[orderHash]/+page.svelte
Labels: enhancement, webapp

#1588 Adding chart support to yaml
  crates/settings/src/chart.rs
  crates/settings/src/plot_source.rs
  crates/settings/src/yaml/dotrain.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1615 move layout.ts tests inline
  packages/webapp/src/routes/deploy/+layout.ts
  packages/webapp/src/routes/deploy/layout.test.ts
Labels: test

#1613 Test handleDepositOrWithdrawTransaction
  packages/ui-components/src/__tests__/transactionStore.test.ts
Labels: test, webapp

#1652 Show user/vault balance on deposit/withdraw
  packages/ui-components/src/lib/components/input/InputTokenAmount.svelte
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
  tauri-app/src/lib/components/ModalVaultWithdraw.svelte
Labels: webapp

#1653 Move outputs above inputs in the gui
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
Labels: webapp

#1657 fix tauri test ci
  .github/workflows/tauri.yaml
Labels: bug

#1654 Update new order indexing logic
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/webapp/src/lib/components/TransactionModal.svelte
Labels: webapp

#1617 Replace walletAddressMatchesOrBlank and viem isAddress checks with accountIsOwner
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/ListViewOrderbookFilters.test.ts
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/__tests__/OrdersListTable.test.ts
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/__tests__/VaultsListTable.test.ts
  packages/ui-components/src/__tests__/WalletConnect.test.ts
  packages/ui-components/src/lib/__mocks__/stores.ts
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/components/tables/OrdersListTable.svelte
  packages/ui-components/src/lib/components/tables/VaultsListTable.svelte
  packages/ui-components/src/lib/providers/wallet/useAccount.ts
  packages/webapp/src/__tests__/DeployModal.test.ts
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/routes/orders/[network]-[orderHash]/+page.svelte
  packages/webapp/src/routes/vaults/+page.svelte
  tauri-app/src/lib/mocks/wallets.ts
  tauri-app/src/lib/stores/settings.test.ts
  tauri-app/src/lib/stores/wallets.ts
  tauri-app/src/routes/orders/+page.svelte
  tauri-app/src/routes/orders/[network]-[orderHash]/+page.svelte
  tauri-app/src/routes/vaults/+page.svelte
Labels: Tauri, webapp

#1651 Consolidate invalidateTanstackQueries into a common function
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/__tests__/TanstackAppTable.test.ts
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/lib/components/TanstackAppTable.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/detail/TanstackOrderQuote.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/components/tables/OrdersListTable.svelte
  packages/ui-components/src/lib/components/tables/VaultBalanceChangesTable.svelte
  packages/ui-components/src/lib/components/tables/VaultsListTable.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/queries/queryClient.ts
  packages/webapp/src/routes/orders/[network]-[orderHash]/+page.svelte
  packages/webapp/src/routes/vaults/[network]-[id]/+page.svelte
  tauri-app/src/routes/orders/[network]-[orderHash]/+page.svelte
  tauri-app/src/routes/vaults/[network]-[id]/+page.svelte
Labels: refactor

#1661 Add rust tests for gui deposits
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/mod.rs
  crates/settings/src/deployment.rs
  crates/settings/src/gui.rs
Labels: test, rust

#1668 Fix button vault hover IDs
  packages/ui-components/src/__tests__/ButtonVaultLink.test.ts
  packages/ui-components/src/lib/components/ButtonVaultLink.svelte
Labels: bug

#1669 Test webapp/layout.ts
  packages/webapp/src/routes/+layout.ts
Labels: test

#1616 Open external links in new tabs
  packages/webapp/src/__tests__/TransactionModal.test.ts
  packages/webapp/src/lib/components/Homepage.svelte
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/lib/components/TransactionModal.svelte
Labels: bug

#1666 Replace "your balance" with "connected wallet balance"
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
  packages/webapp/vite.config.ts
Labels: bug

#1647 Testing page compnent in tauri/orders/[network]-[orderHash]
  packages/ui-components/src/lib/__mocks__/settings.ts
  packages/ui-components/src/lib/__mocks__/stores.ts
  packages/ui-components/src/lib/components/PageHeader.svelte
  packages/ui-components/src/lib/index.ts
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/lib/__mocks__/stores.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/page.test.ts
  tauri-app/src/routes/orders/[network]-[orderHash]/+page.svelte
  tauri-app/src/routes/orders/[network]-[orderHash]/page.test.ts
Labels: bug, test

#1679 Add accounts field yaml parsing logic
  crates/settings/src/accounts.rs
  crates/settings/src/lib.rs
  crates/settings/src/yaml/orderbook.rs
Labels: rust

#1663 Add rust tests fro gui field values
  crates/js_api/src/gui/field_values.rs
Labels: test, rust

#1691 Use sentence case everywhere
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/InputRegistryUrl.test.ts
  packages/ui-components/src/__tests__/InputToken.test.ts
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/lib/components/detail/TanstackOrderQuote.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/components/input/InputOrderHash.svelte
  packages/ui-components/src/lib/components/input/InputRegistryUrl.svelte
  packages/ui-components/src/lib/components/input/InputToken.svelte
  packages/ui-components/src/lib/components/tables/VaultBalanceChangesTable.svelte
  packages/ui-components/src/lib/components/wallet/WalletConnect.svelte
  packages/webapp/src/__tests__/TransactionModal.test.ts
  packages/webapp/src/lib/components/TransactionModal.svelte
Labels: bug

#1681 Add rust tests for gui select tokens
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/select_tokens.rs
Labels: test, rust

#1688 Add test coverage to webapp/+layout.svelte
  packages/ui-components/src/lib/__mocks__/MockComponent.svelte
  packages/webapp/src/lib/__mocks__/MockComponent.svelte
  packages/webapp/src/lib/__mocks__/stores.ts
  packages/webapp/src/lib/components/Homepage.svelte
  packages/webapp/src/routes/+layout.svelte
  packages/webapp/src/routes/layout.test.ts
Labels: test

#1685 Add tests for erc20 file
  crates/common/src/erc20.rs
Labels: test, rust

#1682 Add rust tests for gui state management
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/gui/state_management.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/DepositInput.test.ts
  packages/ui-components/test-setup.ts
Labels: test, rust

#1696 Add missing tests for deposit file
  crates/common/src/deposit.rs
Labels: test, rust

#1701 Add tests for context file
  crates/settings/src/yaml/context.rs
Labels: test, rust

#1695 Fix tx store and update tests
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
Labels: bug

#1683 Add rust tests for gui order operations
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/field_values.rs
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/gui/select_tokens.rs
  crates/js_api/src/gui/state_management.rs
Labels: test, rust

#1699 Add tests for frontmatter file
  crates/common/src/frontmatter.rs
  crates/common/src/lib.rs
  crates/common/src/test_helpers.rs
Labels: test, rust

#1687 Add select token network call tests
  Cargo.lock
  Cargo.toml
  crates/js_api/Cargo.toml
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/field_values.rs
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/gui/select_tokens.rs
  crates/js_api/src/gui/state_management.rs
  crates/js_api/src/lib.rs
Labels: test, rust
