Repository rainlanguage/rain.orderbook, pull requests merged in 2025-01, with the labels that each got.

#1152 Fix populate vault ids on calldata generation
  crates/js_api/src/gui/order_operations.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: webapp

#1136 Adding handlebar support for yaml structs
  crates/settings/src/deployer.rs
  crates/settings/src/deployment.rs
  crates/settings/src/gui.rs
  crates/settings/src/metaboard.rs
  crates/settings/src/network.rs
  crates/settings/src/order.rs
  crates/settings/src/orderbook.rs
  crates/settings/src/scenario.rs
  crates/settings/src/subgraph.rs
  crates/settings/src/token.rs
  crates/settings/src/yaml/context.rs
  crates/settings/src/yaml/dotrain.rs
  crates/settings/src/yaml/mod.rs
  crates/settings/src/yaml/orderbook.rs
Labels: webapp

#1144 Make Raindex logo on homescreen theme-responsive
  tauri-app/src/routes/+page.svelte
Labels: webapp

#1138 Refactor select tokens logic
  crates/common/src/add_order.rs
  crates/common/src/dotrain_order/calldata.rs
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/gui/select_tokens.rs
  crates/settings/src/deployment.rs
  crates/settings/src/gui.rs
  crates/settings/src/order.rs
  crates/settings/src/token.rs
  crates/settings/src/yaml/context.rs
  crates/settings/src/yaml/dotrain.rs
  crates/settings/src/yaml/orderbook.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/webapp/src/routes/deployment/+page.svelte
Labels: rust

#1142 Fix telegram link in sidebar to respect darkmode
  packages/ui-components/src/lib/components/IconTelegram.svelte
  packages/webapp/src/routes/test/+page.svelte
  tauri-app/src/routes/+page.svelte
Labels: webapp

#1164 Fetch settings from raindex.strategies
  packages/webapp/src/lib/settings-12-11-24.json
  packages/webapp/src/lib/settings-12-11-24.yml
  packages/webapp/src/routes/+layout.ts
Labels: webapp

#1157 Improving state serialization/deserialization on DotrainOrderGui
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/state_management.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1167 Make scenario bindings optional in yaml parse method
  crates/settings/src/scenario.rs
  crates/settings/src/yaml/dotrain.rs
Labels: rust

#1168 Update scenario to use scenario key for deployer parsing
  crates/settings/src/scenario.rs
  crates/settings/src/yaml/dotrain.rs
Labels: rust

#1177 01/17/25 deployment UI ci refresh
  .vscode/settings.json
  packages/ui-components/.prettierignore
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/DepositInput.test.ts
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/__tests__/SelectToken.test.ts
  packages/ui-components/src/__tests__/TokenInputOrOutput.test.ts
  packages/ui-components/src/lib/components/deployment/ButtonSelectOption.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSectionHeader.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DepositInput.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
  packages/ui-components/src/lib/components/deployment/TokenInputOrOutput.svelte
  packages/ui-components/src/lib/components/dropdown/DropdownRadio.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/vite.config.ts
  packages/webapp/.prettierignore
  packages/webapp/src/routes/deployment/+page.svelte
  tauri-app/src/lib/services/modal.ts
Labels: webapp

#1146 01/13/25 move vault detail component into vault detail route
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/webapp/src/routes/vaults/[network]-[id]/+page.svelte
  tauri-app/src/routes/vaults/[network]-[id]/+page.svelte
Labels: webapp

#1173 Use Deployer and Orderbook key if network field is not found
  crates/settings/src/deployer.rs
  crates/settings/src/orderbook.rs
Labels: bug, rust

#1200 Yaml parsing speed fix
  crates/settings/src/deployment.rs
  crates/settings/src/gui.rs
  crates/settings/src/order.rs
  crates/settings/src/scenario.rs
  crates/settings/src/yaml/dotrain.rs
Labels: bug, rust

#1208 Update parsing logic with additional context
  crates/js_api/src/gui/mod.rs
  crates/settings/src/deployment.rs
  crates/settings/src/gui.rs
  crates/settings/src/order.rs
  crates/settings/src/yaml/context.rs
  crates/settings/src/yaml/dotrain.rs
Labels: rust

#1206 Vaults and orders routes responsive styles.
  packages/ui-components/src/lib/components/ListViewOrderbookFilters.svelte
  packages/ui-components/src/lib/components/TanstackAppTable.svelte
  packages/ui-components/src/lib/components/input/InputOrderHash.svelte
  packages/ui-components/src/lib/components/tables/VaultsListTable.svelte
  packages/webapp/src/routes/+layout.svelte
Labels: webapp

#1195 Add wagmi stores and deploy transaction using wagmi wallet
  .github/workflows/tauri-release.yml
  .github/workflows/tauri.yaml
  .github/workflows/test-ui-components.yaml
  .github/workflows/test-webapp.yaml
  .github/workflows/vercel-preview.yaml
  .github/workflows/vercel-prod.yaml
  package-lock.json
  package.json
  packages/ui-components/src/lib/__mocks__/mockWeb3Config.ts
  packages/ui-components/src/lib/__mocks__/stores.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/webapp/env.example
  packages/webapp/src/lib/__mocks__/mockWeb3Config.ts
  packages/webapp/src/lib/__mocks__/stores.ts
  packages/webapp/src/lib/__tests__/WalletConnect.test.ts
  packages/webapp/src/lib/chains.ts
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/lib/components/WalletConnect.svelte
  packages/webapp/src/lib/stores/wagmi.test.ts
  packages/webapp/src/lib/stores/wagmi.ts
  packages/webapp/src/routes/+layout.svelte
  packages/webapp/src/routes/+layout.ts
  packages/webapp/src/routes/deploy/+page.svelte
  packages/webapp/test-setup.ts
  packages/webapp/tsconfig.json
  packages/webapp/vite.config.ts
  prep-all.sh
Labels: webapp

#1211 order and vault inner pages responsive
  packages/ui-components/src/lib/components/ButtonVaultLink.svelte
  packages/ui-components/src/lib/components/Hash.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/detail/TanstackOrderQuote.svelte
  packages/ui-components/src/lib/components/detail/TanstackPageContentDetail.svelte
  packages/webapp/src/lib/components/Sidebar.svelte
Labels: webapp

#1147 01/13/25 fix hash links to vaults and orders
  packages/ui-components/src/__tests__/OrderOrVaultHash.test.ts
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/lib/components/OrderOrVaultHash.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/components/tables/VaultsListTable.svelte
  packages/ui-components/src/lib/index.ts
  tauri-app/src/routes/vaults/[network]-[id]/+page.svelte
Labels: webapp

#1201 Show all strats/deployments on deploy route, with links to deployment pages
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/DeploymentTile.test.ts
  packages/ui-components/src/__tests__/DeploymentsSection.test.ts
  packages/ui-components/src/__tests__/StrategySection.test.ts
  packages/ui-components/src/__tests__/WalletConnect.test.ts
  packages/ui-components/src/lib/__mocks__/stores.ts
  packages/ui-components/src/lib/components/deployment/DeploymentPage.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSectionHeader.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentTile.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentsSection.svelte
  packages/ui-components/src/lib/components/deployment/StrategySection.svelte
  packages/ui-components/src/lib/components/deployment/TokenInputOrOutput.svelte
  packages/ui-components/src/lib/components/wallet/WalletConnect.svelte
  packages/ui-components/src/lib/index.ts
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/routes/+layout.ts
  packages/webapp/src/routes/deploy/+layout.svelte
  packages/webapp/src/routes/deploy/+layout.ts
  packages/webapp/src/routes/deploy/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/+page.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.ts
  packages/webapp/src/tests/Sidebar.test.ts
Labels: webapp

#1216 01 28 25 transaction store and modal
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/__mocks__/mockTransactionStore.ts
  packages/ui-components/src/lib/components/deployment/DeploymentPage.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/__tests__/DeployModal.test.ts
  packages/webapp/src/__tests__/Sidebar.test.ts
  packages/webapp/src/__tests__/TransactionModal.test.ts
  packages/webapp/src/lib/components/DeployModal.svelte
  packages/webapp/src/lib/components/TransactionModal.svelte
  packages/webapp/src/lib/services/modal.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
Labels: webapp
