Repository rainlanguage/rain.orderbook, pull requests merged in 2025-03, with the labels that each got.

#1387 Change order links to orderHash not order IDs
  crates/js_api/src/subgraph/order.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/types/order.rs
  crates/subgraph/tests/order_test.rs
  crates/subgraph/tests/snapshots/order_test__orders_query_gql_output.snap
  packages/orderbook/test/js_api/order.test.ts
  packages/ui-components/src/__tests__/OrderDetail.test.svelte
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/__tests__/OrderOrVaultHash.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/components/OrderOrVaultHash.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/tables/OrdersListTable.svelte
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/webapp/src/lib/components/TransactionModal.svelte
  packages/webapp/src/routes/orders/[network]-[orderHash]/+page.svelte
  tauri-app/src/routes/orders/[network]-[orderHash]/+page.svelte
Labels: webapp

#1388 Add connector for walletconnect
  packages/webapp/src/routes/+layout.svelte
Labels: webapp

#1389 Replace icons for tauri homepage
  tauri-app/src/lib/components/Sidebar.svelte
  tauri-app/src/routes/+page.svelte
Labels: Tauri

#1384 1379 if the given registry link does have an error we need to show it to the user
  packages/ui-components/src/__tests__/InvalidStrategiesSection.test.ts
  packages/ui-components/src/__tests__/ValidStrategiesSection.test.ts
  packages/ui-components/src/lib/components/deployment/InvalidStrategiesSection.svelte
  packages/ui-components/src/lib/components/deployment/StrategiesSection.svelte
  packages/ui-components/src/lib/components/deployment/StrategyShortTile.svelte
  packages/ui-components/src/lib/components/deployment/ValidStrategiesSection.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/types/strategy.ts
  packages/webapp/src/routes/deploy/+layout.ts
  packages/webapp/src/routes/deploy/+page.svelte
Labels: webapp

#1425 Show selected field value, not default, if one has been chosen
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
Labels: bug

#1411 Add explorer links for pending deployments
  packages/ui-components/src/__tests__/getExplorerLink.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/services/getExplorerLink.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/webapp/src/lib/components/TransactionModal.svelte
Labels: webapp

#1455 Display truncated eth address if wallet is connected
  package-lock.json
  package.json
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/WalletConnect.test.ts
  packages/ui-components/src/lib/__mocks__/stores.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/wallet/WalletConnect.svelte
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
Labels: webapp

#1442 Update function parameters
  tauri-app/src/lib/services/authoringMeta.ts
  tauri-app/src/lib/services/order.ts
  tauri-app/src/routes/orders/add/+page.svelte
Labels: bug, Tauri

#1432 Cleanup strategies section
  packages/ui-components/src/__tests__/InvalidStrategiesSection.test.ts
  packages/ui-components/src/__tests__/StrategyPage.test.ts
  packages/ui-components/src/__tests__/StrategyShortTile.test.ts
  packages/ui-components/src/__tests__/ValidStrategiesSection.test.ts
  packages/ui-components/src/lib/components/deployment/InvalidStrategiesSection.svelte
  packages/ui-components/src/lib/components/deployment/StrategiesSection.svelte
  packages/ui-components/src/lib/components/deployment/StrategyPage.svelte
  packages/ui-components/src/lib/components/deployment/StrategyShortTile.svelte
  packages/ui-components/src/lib/components/deployment/ValidStrategiesSection.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/types/strategy.ts
  packages/webapp/src/routes/deploy/+layout.ts
  packages/webapp/src/routes/deploy/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/+layout.ts
Labels: webapp

#1431 03/06/25 Cleanup deployments section
  packages/ui-components/src/__tests__/DeploymentsSection.test.ts
  packages/ui-components/src/__tests__/StrategyPage.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentsSection.svelte
Labels: webapp

#1451 Add a method to get current deployment details
  crates/js_api/src/gui/mod.rs
  crates/settings/src/gui.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1466 Remove replace select token function in gui sdk
  crates/js_api/src/gui/select_tokens.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/SelectToken.test.ts
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
Labels: rust, webapp

#1467 Fix CodeMirrorRainlang prop
  packages/ui-components/src/lib/components/CodeMirrorRainlang.svelte
  tauri-app/src/routes/orders/add/+page.svelte
Labels: bug, webapp

#1488 Add useGui to DeploymentSteps and GuiProvider
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/errors/DeploymentStepsError.ts
  packages/ui-components/src/lib/hooks/useGui.test.ts
  packages/ui-components/src/lib/hooks/useGui.ts
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/providers/GuiProvider.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
Labels: webapp

#1452 Implement new wasm macro to base DotrainOrderGui methods
  Cargo.lock
  Cargo.toml
  crates/common/src/dotrain_order/mod.rs
  crates/js_api/src/gui/mod.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/DeploymentsSection.test.ts
  packages/ui-components/src/__tests__/DepositInput.test.ts
  packages/ui-components/src/__tests__/StrategyPage.test.ts
  packages/ui-components/src/__tests__/TokenIOInput.test.ts
  packages/ui-components/src/lib/components/deployment/ComposedRainlangModal.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentsSection.svelte
  packages/ui-components/src/lib/components/deployment/DepositInput.svelte
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
  packages/ui-components/src/lib/components/deployment/StrategyPage.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
  packages/ui-components/test-setup.ts
  packages/webapp/src/__tests__/handleGuiInitialization.test.ts
  packages/webapp/src/lib/services/handleGuiInitialization.ts
  packages/webapp/src/routes/deploy/+layout.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+layout.ts
  packages/webapp/test-setup.ts
  tauri-app/src-tauri/Cargo.lock
Labels: rust, webapp

#1513 Tested validateStrategies function
  packages/ui-components/src/lib/services/index.ts
  packages/ui-components/src/lib/services/registry.ts
  packages/webapp/src/routes/deploy/+layout.ts
  packages/webapp/src/routes/deploy/+page.svelte
Labels: bug

#1456 Implement wasm macro on DotrainOrderGui deposit methods
  crates/js_api/src/gui/deposits.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/DepositInput.test.ts
  packages/ui-components/src/lib/components/deployment/DepositInput.svelte
Labels: rust

#1489 Remove TokenIO Section
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOSection.svelte
Labels: webapp

#1457 Implement wasm macro on DotrainOrderGui field values methods
  crates/js_api/src/gui/field_values.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
  packages/ui-components/test-setup.ts
Labels: rust

#1490 Remove deposit section
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DepositsSection.svelte
Labels: webapp

#1491 Remove field definition section
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionsSection.svelte
Labels: webapp

#1458 Implement wasm macro on DotrainOrderGui order operations methods
  crates/js_api/src/gui/order_operations.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/TokenIOInput.test.ts
  packages/ui-components/src/__tests__/getDeploymentTransactionArgs.test.ts
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
  packages/ui-components/src/lib/components/deployment/getDeploymentTransactionArgs.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/ui-components/test-setup.ts
  packages/webapp/src/__tests__/DeployModal.test.ts
Labels: rust, webapp

#1526 update registry commit
  packages/webapp/src/lib/constants.ts
Labels: enhancement

#1460 Implement wasm macro on DotrainOrderGui state management methods
  crates/js_api/src/gui/state_management.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/handleShareChoices.test.ts
  packages/ui-components/src/lib/services/handleShareChoices.ts
  packages/ui-components/test-setup.ts
  packages/webapp/src/__tests__/handleGuiInitialization.test.ts
  packages/webapp/src/lib/services/handleGuiInitialization.ts
  packages/webapp/test-setup.ts
Labels: rust, webapp

#1506 Add header to Orders table
  packages/ui-components/src/lib/components/tables/OrdersListTable.svelte
Labels: webapp

#1531 pin deps
  package-lock.json
  package.json
  packages/orderbook/package.json
  packages/ui-components/package.json
  packages/webapp/package.json
  tauri-app/package.json
Labels: general update

#1521 fix tauri release issues
  .github/workflows/tauri-release.yml
  flake.lock
Labels: bug, general update

#1515 Test for layout load on deploy/[strategyName]/[deploymentKey]
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/layout.test.ts
Labels: webapp

#1463 Add readable error messages
  crates/js_api/src/gui/mod.rs
  crates/settings/src/deployer.rs
  crates/settings/src/deployment.rs
  crates/settings/src/gui.rs
  crates/settings/src/metaboard.rs
  crates/settings/src/network.rs
  crates/settings/src/order.rs
  crates/settings/src/orderbook.rs
  crates/settings/src/scenario.rs
  crates/settings/src/subgraph.rs
  crates/settings/src/token.rs
  crates/settings/src/yaml/context.rs
  crates/settings/src/yaml/dotrain.rs
  crates/settings/src/yaml/mod.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1469 Tauri app fixes (save button - undefined deployer address)
  crates/common/src/dotrain_add_order_lsp.rs
  packages/ui-components/src/__tests__/CodeMirrorDotrain.test.ts
  packages/ui-components/src/lib/components/CodeMirrorDotrain.svelte
  packages/webapp/src/routes/test/+page.svelte
  tauri-app/src/routes/orders/add/+page.svelte
Labels: bug, rust

#1471 Add function to get yaml fields
  crates/js_api/src/gui/field_values.rs
  crates/js_api/src/gui/state_management.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust
