Repository rainlanguage/rain.orderbook, pull requests merged in 2025-02, with the labels that each got.

#1230 Fix and gui yaml parsing
  crates/settings/src/order.rs
  crates/settings/src/yaml/dotrain.rs
Labels: bug, rust

#1202 Adding wasm bindings for vault deposit/withdraw calldata generation
  crates/common/src/deposit.rs
  crates/common/src/dotrain_order/calldata.rs
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/subgraph/mod.rs
  crates/js_api/src/subgraph/order.rs
  crates/js_api/src/subgraph/vault.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/orderbook/test/js_api/order.test.ts
  packages/orderbook/test/js_api/vault.test.ts
  tauri-app/src-tauri/src/commands/vault.rs
  tauri-app/src/lib/components/ModalVaultDeposit.svelte
  tauri-app/src/lib/components/ModalVaultDepositGeneric.svelte
  tauri-app/src/lib/services/vault.ts
Labels: js/wasm, rust

#1213 01 23 2025 add depositwithdraw buttons to orders
  packages/ui-components/src/__tests__/InputTokenAmount.test.ts
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/components/detail/DepositOrWithdrawButtons.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/components/input/InputTokenAmount.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/__tests__/TransactionModal.test.ts
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
  packages/webapp/src/lib/components/TransactionModal.svelte
  packages/webapp/src/lib/services/modal.ts
  packages/webapp/src/lib/stores/wagmi.ts
  packages/webapp/src/routes/orders/[network]-[id]/+page.svelte
  packages/webapp/src/routes/vaults/[network]-[id]/+page.svelte
  tauri-app/src/lib/components/InputTokenAmount.svelte
  tauri-app/src/lib/components/InputTokenAmount.test.ts
  tauri-app/src/lib/components/ModalVaultDeposit.svelte
  tauri-app/src/lib/components/ModalVaultDepositGeneric.svelte
  tauri-app/src/lib/components/ModalVaultWithdraw.svelte
  tauri-app/src/routes/orders/[network]-[id]/+page.svelte
Labels: webapp

#1234 Add component to show rainlang and fix scenario binding update function
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/order_operations.rs
  crates/settings/src/scenario.rs
  crates/settings/src/yaml/dotrain.rs
  packages/ui-components/src/__tests__/ComposedRainlangModal.test.ts
  packages/ui-components/src/lib/components/deployment/ComposedRainlangModal.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
Labels: rust, webapp

#1238 Make deposit presets an optional field
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/mod.rs
  crates/settings/src/config_source.rs
  crates/settings/src/gui.rs
  crates/settings/src/yaml/dotrain.rs
Labels: rust

#1212 Refactoring state serialization/deserialization
  .vscode/settings.json
  Cargo.lock
  crates/js_api/Cargo.toml
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/state_management.rs
  crates/settings/src/gui.rs
  crates/settings/src/order.rs
  crates/settings/src/yaml/dotrain.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/orderbook/test/js_api/order.test.ts
Labels: js/wasm, rust

#1231 Pass correct error from tokenSelect wasm
  packages/ui-components/src/__tests__/SelectToken.test.ts
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
  packages/ui-components/src/lib/components/deployment/TokenInputOrOutput.svelte
Labels: webapp

#1239 fix paste not refreshing select tokens
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
Labels: webapp

#1228 Review choices and sharing links for deployments
  packages/orderbook/test/js_api/vault.test.ts
  packages/ui-components/src/__tests__/DeploymentSectionHeader.test.ts
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/__tests__/SelectToken.test.ts
  packages/ui-components/src/__tests__/TokenIOInput.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentPage.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSectionHeader.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DepositInput.svelte
  packages/ui-components/src/lib/components/deployment/DepositsSection.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionsSection.svelte
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
  packages/ui-components/src/lib/components/deployment/SelectTokensSection.svelte
  packages/ui-components/src/lib/components/deployment/StrategySection.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOSection.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/test-setup.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.ts
Labels: webapp

#1246 Add padding to page header breadcrumbs
  packages/ui-components/src/lib/components/PageHeader.svelte
Labels: webapp

#1243 Improve error messages for yaml parsing functions
  crates/settings/src/deployer.rs
  crates/settings/src/deployment.rs
  crates/settings/src/gui.rs
  crates/settings/src/metaboard.rs
  crates/settings/src/network.rs
  crates/settings/src/order.rs
  crates/settings/src/orderbook.rs
  crates/settings/src/scenario.rs
  crates/settings/src/subgraph.rs
  crates/settings/src/token.rs
  crates/settings/src/yaml/dotrain.rs
  crates/settings/src/yaml/mod.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1254 new registry
  packages/webapp/src/lib/stores/registry.ts
Labels: webapp

#1255 Adding remove order button to order details page on webapp
  crates/common/src/js_api/mod.rs
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/webapp/src/__tests__/OrderRemoveModal.test.ts
  packages/webapp/src/lib/components/OrderRemoveModal.svelte
  packages/webapp/src/lib/services/modal.ts
  packages/webapp/src/routes/orders/[network]-[id]/+page.svelte
  tauri-app/src/routes/orders/[network]-[id]/+page.svelte
Labels: rust, webapp

#1247 Add homepage
  packages/ui-components/src/lib/components/wallet/WalletConnect.svelte
  packages/webapp/src/app.html
  packages/webapp/src/lib/components/Homepage.svelte
  packages/webapp/src/routes/+layout.svelte
  packages/webapp/tailwind.config.ts
Labels: webapp

#1258 2/10/25 remove use of sveltekit goto
  packages/ui-components/src/__tests__/ButtonVaultLink.test.ts
  packages/ui-components/src/__tests__/DeploymentTile.test.ts
  packages/ui-components/src/__tests__/OrderOrVaultHash.test.ts
  packages/ui-components/src/lib/components/ButtonVaultLink.svelte
  packages/ui-components/src/lib/components/OrderOrVaultHash.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentTile.svelte
Labels: webapp

#1256 switch vault address for ID in display
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
Labels: webapp

#1264 Fix unhandled get token info error
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
Labels: webapp

#1269 Add missing field checks for js api
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/field_values.rs
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/order_operations.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1266 Improve ERC20 token info error messages
  crates/common/src/erc20.rs
Labels: rust, webapp

#1271 Pass on styling
  packages/ui-components/src/lib/components/ButtonVaultLink.svelte
  packages/ui-components/src/lib/components/PageHeader.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentTile.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentsSection.svelte
  packages/ui-components/src/lib/components/deployment/StrategySection.svelte
  packages/ui-components/src/lib/components/detail/DepositOrWithdrawButtons.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/routes/deploy/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/+layout.svelte
  packages/webapp/src/routes/orders/+page.svelte
Labels: webapp

#1278 Fix vault ids defaulting to 0x0 after deserializing
  crates/js_api/src/gui/state_management.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: bug, rust, webapp

#1290 Token selection checks and getting all vault ids
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/gui/select_tokens.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/TokenIOInput.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
Labels: rust

#1291 Creating compose rainlang function in rust
  crates/js_api/src/gui/mod.rs
  packages/ui-components/src/__tests__/ComposedRainlangModal.test.ts
  packages/ui-components/src/lib/components/deployment/ComposedRainlangModal.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
Labels: rust

#1289 02/13/25 switch chain before checking user's balance
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
Labels: webapp

#1296 Categorize vaults in order details page
  crates/js_api/src/subgraph/order.rs
  packages/orderbook/test/js_api/order.test.ts
  packages/ui-components/src/__tests__/OrderDetail.test.svelte
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
Labels: rust, webapp

#1283 2/12/25 add markdown descriptions
  crates/settings/src/gui.rs
  crates/settings/src/yaml/dotrain.rs
  package-lock.json
  package.json
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/package.json
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/DeploymentsSection.test.ts
  packages/ui-components/src/__tests__/StrategyPage.test.ts
  packages/ui-components/src/__tests__/StrategySection.test.ts
  packages/ui-components/src/__tests__/StrategyShortTile.test.ts
  packages/ui-components/src/lib/__mocks__/stores.ts
  packages/ui-components/src/lib/components/deployment/DeploymentPage.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentTile.svelte
  packages/ui-components/src/lib/components/deployment/StrategyPage.svelte
  packages/ui-components/src/lib/components/deployment/StrategySection.svelte
  packages/ui-components/src/lib/components/deployment/StrategyShortTile.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/services/index.ts
  packages/ui-components/src/lib/services/registry.ts
  packages/webapp/env.example
  packages/webapp/postcss.config.js
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/lib/constants.ts
  packages/webapp/src/lib/stores/raw-dotrain.ts
  packages/webapp/src/lib/stores/registry.ts
  packages/webapp/src/routes/deploy/+layout.ts
  packages/webapp/src/routes/deploy/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/+layout.svelte
  packages/webapp/src/routes/deploy/[strategyName]/+layout.ts
  packages/webapp/src/routes/deploy/[strategyName]/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/+page.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+layout.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.ts
  packages/webapp/src/routes/deploy/getFileRegistry.ts
  packages/webapp/tailwind.config.ts
Labels: webapp

#1298 share button fix
  packages/ui-components/src/__tests__/handleShareChoices.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/services/handleShareChoices.ts
  packages/webapp/src/lib/services/handleUpdateGuiState.ts
Labels: bug, webapp

#1299 Disable get token info calls if not all select tokens are filled
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
Labels: bug, webapp

#1297 Add function to get a single deployment detail
  crates/js_api/src/gui/mod.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+layout.ts
Labels: rust, webapp

#1295 02/13/25 Add_order.rs query for new deployments, and await new deployment as part of tx flow
  crates/js_api/src/subgraph/add_order.rs
  crates/js_api/src/subgraph/mod.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/types/add_order.rs
  crates/subgraph/src/types/common.rs
  crates/subgraph/src/types/mod.rs
  packages/orderbook/test/js_api/addOrder.test.ts
  packages/orderbook/test/js_api/transaction.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/webapp/src/lib/components/DeployModal.svelte
  packages/webapp/src/lib/components/TransactionModal.svelte
  packages/webapp/src/lib/services/modal.ts
Labels: webapp

#1300 Set vault id to None if given string is undefined or empty
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/gui/state_management.rs
  crates/settings/src/order.rs
  crates/settings/src/yaml/dotrain.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
Labels: bug, rust

#1301 02/14/25 Add disclaimer modal and move + test calldata generation
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/DisclaimerModal.test.ts
  packages/ui-components/src/__tests__/getDeploymentTransactionArgs.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DisclaimerModal.svelte
  packages/ui-components/src/lib/components/deployment/getDeploymentTransactionArgs.ts
  packages/ui-components/src/lib/components/wallet/WalletConnect.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/lib/components/DeployModal.svelte
  packages/webapp/src/lib/components/Sidebar.svelte
  packages/webapp/src/lib/services/modal.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
Labels: webapp

#1306 updated registry and fixed title on deployment page
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/webapp/src/lib/constants.ts
  packages/webapp/src/routes/deploy/[strategyName]/+layout.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
Labels: webapp

#1313 Removing deposits on empty amount
  crates/js_api/src/gui/deposits.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: bug, rust

#1314 Check for order quote response length
  packages/ui-components/src/lib/components/detail/TanstackOrderQuote.svelte
Labels: bug, webapp

#1319 Making deposit calldata generation optional
  crates/js_api/src/gui/order_operations.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/getDeploymentTransactionArgs.test.ts
  packages/ui-components/src/lib/components/deployment/getDeploymentTransactionArgs.ts
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/lib/components/DeployModal.svelte
Labels: rust

#1341 Add any functions for deposits and vault ids
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/order_operations.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
Labels: rust, webapp

#1330 Move modal types into ui-components and refactor their usage
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/OrderDetail.test.svelte
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/detail/DepositOrWithdrawButtons.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/detail/TanstackOrderQuote.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/index.ts
  packages/ui-components/src/lib/types/modal.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/__tests__/DeployModal.test.ts
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/__tests__/OrderRemoveModal.test.ts
  packages/webapp/src/lib/components/DeployModal.svelte
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
  packages/webapp/src/lib/components/OrderRemoveModal.svelte
  packages/webapp/src/lib/services/modal.ts
  tauri-app/src/routes/orders/[network]-[id]/+page.svelte
Labels: webapp

#1342 Move get deployment transaction args function to rust
  crates/common/src/dotrain_order/calldata.rs
  crates/js_api/src/gui/order_operations.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/getDeploymentTransactionArgs.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/getDeploymentTransactionArgs.ts
Labels: rust, webapp

#1339 RemoveEvents index await
  crates/cli/src/commands/order/detail.rs
  crates/cli/src/commands/order/list.rs
  crates/js_api/src/subgraph/mod.rs
  crates/js_api/src/subgraph/remove_order.rs
  crates/quote/src/cli/mod.rs
  crates/quote/src/order_quotes.rs
  crates/quote/src/quote.rs
  crates/subgraph/src/orderbook_client.rs
  crates/subgraph/src/performance/order_performance.rs
  crates/subgraph/src/types/common.rs
  crates/subgraph/src/types/mod.rs
  crates/subgraph/src/types/order_detail_traits.rs
  crates/subgraph/src/types/remove_order.rs
  crates/subgraph/tests/snapshots/batch_order_test__batch_order_query_gql_output.snap
  crates/subgraph/tests/snapshots/order_test__orders_query_gql_output.snap
  crates/subgraph/tests/snapshots/orders_test__orders_query_gql_output.snap
  packages/orderbook/test/js_api/addOrder.test.ts
  packages/orderbook/test/js_api/order.test.ts
  packages/orderbook/test/js_api/removeOrder.test.ts
  packages/orderbook/test/js_api/vault.test.ts
  packages/orderbook/test/quote/test.test.ts
  packages/ui-components/src/__tests__/OrderDetail.test.svelte
  packages/ui-components/src/__tests__/transactionStore.test.ts
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/stores/transactionStore.ts
  packages/ui-components/src/lib/types/transaction.ts
  packages/webapp/src/lib/components/TransactionModal.svelte
  tauri-app/src-tauri/src/commands/order_quote.rs
Labels: webapp

#1343 create helper function for getting gui deposit in deposits
  crates/js_api/src/gui/deposits.rs
Labels: rust

#1357 Remove duplicate code in state management
  Cargo.lock
  crates/js_api/Cargo.toml
  crates/js_api/src/gui/state_management.rs
Labels: rust

#1361 Move URL update function to gui as a callback
  crates/js_api/src/gui/deposits.rs
  crates/js_api/src/gui/field_values.rs
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/gui/select_tokens.rs
  crates/js_api/src/gui/state_management.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/DepositInput.test.ts
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/__tests__/SelectToken.test.ts
  packages/ui-components/src/__tests__/TokenIOInput.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/DepositInput.svelte
  packages/ui-components/src/lib/components/deployment/DepositsSection.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionsSection.svelte
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
  packages/ui-components/src/lib/components/deployment/SelectTokensSection.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOSection.svelte
  packages/webapp/src/lib/services/handleUpdateGuiState.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
Labels: rust, webapp

#1356 Add checking state for deposit/withdraw button to prevent modal from showing early
  packages/webapp/src/__tests__/DepositOrWithdrawModal.test.ts
  packages/webapp/src/lib/components/DepositOrWithdrawModal.svelte
Labels: webapp

#1362 Adding new error class for better error handling
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/errors/DeploymentStepsError.ts
  packages/ui-components/src/lib/errors/index.ts
Labels: webapp

#1329 1303 order page isnt polling and can be out of sync
  packages/ui-components/src/__tests__/OrderDetail.test.svelte
  packages/ui-components/src/__tests__/OrderDetail.test.ts
  packages/ui-components/src/__tests__/TanstackAppTable.test.svelte
  packages/ui-components/src/__tests__/TanstackAppTable.test.ts
  packages/ui-components/src/__tests__/TanstackOrderQuote.test.ts
  packages/ui-components/src/__tests__/VaultDetail.test.ts
  packages/ui-components/src/lib/components/TanstackAppTable.svelte
  packages/ui-components/src/lib/components/charts/LightweightChart.svelte
  packages/ui-components/src/lib/components/detail/OrderDetail.svelte
  packages/ui-components/src/lib/components/detail/TanstackOrderQuote.svelte
  packages/ui-components/src/lib/components/detail/VaultDetail.svelte
  packages/ui-components/src/lib/components/icon/Refresh.svelte
  packages/ui-components/src/lib/components/tables/OrderAPY.svelte
  packages/ui-components/src/lib/components/tables/OrderTradesListTable.svelte
  packages/ui-components/src/lib/components/tables/OrderVaultsVolTable.svelte
  packages/ui-components/src/lib/components/tables/OrdersListTable.svelte
  packages/ui-components/src/lib/components/tables/VaultBalanceChangesTable.svelte
  packages/ui-components/src/lib/components/tables/VaultsListTable.svelte
  packages/ui-components/src/lib/queries/queryClient.ts
  packages/ui-components/src/lib/stores/queryClient.ts
  packages/webapp/src/routes/orders/[network]-[id]/+page.svelte
  packages/webapp/src/routes/vaults/[network]-[id]/+page.svelte
Labels: webapp

#1366 2025 02 21 fix missing logos
  tauri-app/src/lib/components/Sidebar.svelte
  tauri-app/src/routes/+page.svelte
Labels: bug

#1344 Update field descriptions on select token change
  crates/js_api/src/gui/mod.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/SelectToken.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
Labels: rust, webapp

#1355 02/19/25 remove null gui from deployment steps
  packages/orderbook/test/js_api/order.test.ts
  packages/orderbook/test/quote/test.test.ts
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/__tests__/TokenIOInput.test.ts
  packages/ui-components/src/__tests__/getDeploymentTransactionArgs.test.ts
  packages/ui-components/src/lib/components/deployment/ComposedRainlangModal.svelte
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/SelectToken.svelte
  packages/ui-components/src/lib/components/deployment/TokenIOInput.svelte
  packages/ui-components/src/lib/components/deployment/getDeploymentTransactionArgs.ts
  packages/webapp/src/__tests__/handleGuiInitialization.test.ts
  packages/webapp/src/lib/services/handleGuiInitialization.ts
  packages/webapp/src/routes/deploy/[strategyName]/[deploymentKey]/+page.svelte
Labels: webapp

#1358 Remove calldata file in dotrain order and refactor order operations
  crates/common/src/dotrain_order/calldata.rs
  crates/common/src/dotrain_order/mod.rs
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/order_operations.rs
  crates/js_api/src/subgraph/mod.rs
  packages/orderbook/test/js_api/gui.test.ts
Labels: rust

#1377 Fix token info bug
  crates/js_api/src/gui/mod.rs
  crates/js_api/src/gui/select_tokens.rs
  crates/settings/src/order.rs
  crates/settings/src/yaml/dotrain.rs
Labels: bug, rust

#1378 State loading issue
  packages/ui-components/src/__tests__/DeploymentSteps.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
Labels: bug, webapp

#1380 Implementing default value support for field values
  crates/js_api/src/gui/field_values.rs
  crates/settings/src/gui.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/lib/components/deployment/DeploymentSteps.svelte
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
Labels: rust, webapp

#1381 Add `show-custom-field` flag to gui and update UI
  crates/settings/src/gui.rs
  packages/orderbook/test/js_api/gui.test.ts
  packages/ui-components/src/__tests__/FieldDefinitionInput.test.ts
  packages/ui-components/src/lib/components/deployment/FieldDefinitionInput.svelte
Labels: rust, webapp
